### ISSUE TITLE
Unable to create a owning adapter

### ISSUE THREAD

**Issue by Hedgehogo** [SUPERCILEX/io-adapters#2]
Although types are described like `FmtToIo<W>`, it is only possible to create examples from special cases like `FmtToIo<&mut W>`. 

This can be fixed by changing the description of the `WriteExtension` trait to:
```rs
pub trait WriteExtension<T> {
    type Adapter;

    fn write_adapter(self) -> Self::Adapter;
}
```

And implementations can be fixed like (`io::Write` is implemented for `&mut W`):
```rs
impl<W: io::Write> WriteExtension<FmtToIo<W>> for W {
    type Adapter = FmtToIo<W>;

    fn write_adapter(self) -> FmtToIo<W> {
        FmtToIo {
            inner: self,
            error: None,
        }
    }
}
```

However such a solution would break the API, a softer option might be to add a `new()` function to the `FmtToIo` and `IoToHasher` structures, which would already take `T` at once instead of `&mut T`:
```rs
impl<W: io::Write> FmtToIo<W> {
    pub fn new(inner: W) -> Self {
        Self { inner, error: None }
    }
}
```

P.S. I would do a fork and a pull request if the formatting and compilation settings you use could be posted so I can run the tests successfully (all my settings are standard).

**Comment by SUPERCILEX** [comment]
I think this led to conflicting trait impls, but I recently read this so could probably figure out a way around it: https://willcrichton.net/notes/defeating-coherence-rust/

**Comment by SUPERCILEX** [comment]
You should be able to get things to compile just with nightly and then I can clean up whatever the lints whine about. Don't have access to a computer for another few weeks so will be slow.

**Comment by Hedgehogo** [comment]
> I think this led to conflicting trait impls, but I recently read this so could probably figure out a way around it: https://willcrichton.net/notes/defeating-coherence-rust/

It won't cause a conflict, I'm suggesting substituting an implementation, not adding another one. However, as I said above this would break the API, because now calling `write_adapter` on a non `&mut` will return `Adapter<W>` instead of `Adapter<&mut W>`.

**Comment by SUPERCILEX** [comment]
I don't care about API breakage, so I'd prefer we fix the extension trait. IIRC I didn't want people to interface with the specific trait impls and instead just import the extension trait so they'd automatically get all the conversions in one go.
